language: python
python:
  - 3.6
install:
  - make install
script:
  - make test
after_success:
  - curl -k -u $ZEROBUGUID:$ZEROBUGTOKEN --request POST -H "Content-Type:application/json" -d '{"pit":"131","targetid":"oX$*smjwLJf5!qVRTurh1598404714","ci":"Travis CI","tipo":"14"}' https://zerobug.co/ScanTarget/
